export const AUTH_UPDATE_FETCHING = 'AUTH_UPDATE_FETCHING';
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';
export const AUTH_UPDATE_LOGIN_ERROR = 'AUTH_UPDATE_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';